/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_easivend_evprotocol_EVprotocol */

#ifndef _Included_com_easivend_evprotocol_EVprotocol
#define _Included_com_easivend_evprotocol_EVprotocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_easivend_evprotocol_EVprotocol
 * Method:    vmcStart
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_easivend_evprotocol_EVprotocol_vmcStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_easivend_evprotocol_EVprotocol
 * Method:    vmcStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_easivend_evprotocol_EVprotocol_vmcStop
  (JNIEnv *, jobject);

/*
 * Class:     com_easivend_evprotocol_EVprotocol
 * Method:    trade
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_easivend_evprotocol_EVprotocol_trade
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
